ARG BASE_IMAGE_BUILD_FROM
FROM --platform=$BUILDPLATFORM ${BASE_IMAGE_BUILD_FROM}

WORKDIR /app

COPY ./ ./

RUN tar zxvf ./skywalking/apache-skywalking-java-agent-8.14.0.tgz
RUN --mount=type=cache,target=/root/.m2 mvn dependency:go-offline -B -q