spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  shutdown: graceful
logging:
  level:
    root: info

##### 以上為 3rd lib 設定, 以下為專案內設定

authenticate:
  oldUapiToken:
    pwdAesIV: www.jkos_o2o.com
    pwdAesKey: JKOS_O2OPlatform