spring:
  profiles:
    active: local
  application:
    name: appsvc-api
  datasource:
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=TRUE
    username: root
    password: root
server:
  port: 8080
  servlet:
    contextPath: /appsvc/api

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health

api-version: v1

jkos-uapi:
  base-url: https://sit-uapi-inner.jkos.app/Service/
  myMessageDownTime: "2025-03-01T00:00:00"
msg-hub:
  base-url: https://sit-msghub.jkos.app/

authenticate:
  oldUapiToken:
    pwdAesIV: www.jkos_o2o.com
    pwdAesKey: JKOS_O2OPlatform