spring:
  profiles:
    active: local
  application:
    name: appsvc-api
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: api
    password: api
    driverClassName: org.h2.Driver
    hikari:
      maximumPoolSize: 5
      minimumIdle: 5
server:
  port: 8080
  servlet:
    contextPath: /appsvc/api
##### 以上為 3rd lib 設定, 以下為專案內設定

jkos:
  uapi:
    base-url: https://sit-uapi-inner.jkos.app/Service/
    my-jkos-message-offline-month: 2025-03
msg-hub:
  base-url: https://sit-msghub.jkos.app/

authenticate:
  oldUapiToken:
    pwdAesIV: www.jkos_o2o.com
    pwdAesKey: JKOS_O2OPlatform